proxied-appfog: 
  adapter: mysql2 
  database: d7d34f07ef62a42a99706b16d54b520cd
  username: ugjgEt62k60Ud 
  password: pnXvLJ9Xh9MH5 
  port: 10000 
  host: 127.0.0.1
  
development: 
  adapter: mysql2 
  database: d7d34f07ef62a42a99706b16d54b520cd
  username: ugjgEt62k60Ud 
  password: pnXvLJ9Xh9MH5 
  port: 10000 
  host: 127.0.0.1