class AdminController < ApplicationController
  layout 'application', :except => [:print_timesheet]
  before_filter :check_session
  
  def timesheet
    @week = Week.find(params[:id])
    respond_to do |format|
           format.js
           format.pdf {
             render :pdf => "timesheet", :header => { :font_size => '8', :right => '[page] of [toPage]' }, :footer => {:font_size => '8', :right => 'Generated by jottinx.com' }
          }
         end
  end
end
